-- YANGI SUPABASE LOYIHASI uchun to'liq jadvallar (yangi AI bot).
-- Supabase → SQL Editor → New query → shu kodni joylab "Run" bosing.
-- Bir necha marta ishga tushirilsa ham xavfsiz (if not exists).
-- Rasmlar uchun "ai-uploads" papkasi (Storage) server tomonidan o'zi yaratiladi.

-- Buyurtmalar
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  service text not null,
  color text,
  side text,
  format text,
  qty integer,
  total numeric,
  free_pages_used integer not null default 0,
  telegram_user_id bigint,
  telegram_username text,
  telegram_name text,
  status text not null default 'active',
  telegram_message_id bigint,
  hidden_by_customer boolean not null default false,
  details jsonb,     -- mavzu, maydonlar, qaysi bot
  file_id text,      -- tayyor faylning Telegram file_id si
  file_name text
);
create index if not exists orders_telegram_user_id_idx on orders (telegram_user_id, created_at desc);
create index if not exists orders_telegram_message_id_idx on orders (telegram_message_id);

-- Foydalanuvchilar (e'lon yuborish va statistika uchun)
create table if not exists users (
  telegram_user_id bigint primary key,
  username text,
  first_name text,
  last_seen timestamptz,
  free_pages integer not null default 0,
  referral_count integer not null default 0,
  reward_3_given boolean not null default false,
  reward_5_given boolean not null default false,
  created_at timestamptz not null default now()
);

-- Ilovaga kirishlar (statistika)
create table if not exists visits (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint,
  created_at timestamptz not null default now()
);

-- Referallar (confirmed_at — AI botda do'st birinchi buyurtmasini olgan vaqt)
create table if not exists referrals (
  id bigint generated by default as identity primary key,
  referrer_id bigint not null,
  referred_id bigint not null unique,
  created_at timestamptz not null default now()
);

-- AI bot referal tizimi uchun qo'shimcha ustunlar (eski loyihaga ham qo'shiladi)
alter table users add column if not exists ai_credits integer not null default 0;   -- bepul AI buyurtmalar (bonus)
alter table users add column if not exists ai_referrals integer not null default 0; -- tasdiqlangan do'stlar soni
alter table referrals add column if not exists confirmed_at timestamptz;
create index if not exists referrals_referrer_id_idx on referrals (referrer_id);

-- Ma'lumotlar faqat server (service key) orqali o'qiladi/yoziladi:
-- RLS yoqiladi va hech qanday ochiq ruxsat berilmaydi.
alter table orders enable row level security;
alter table users enable row level security;
alter table visits enable row level security;
alter table referrals enable row level security;
